package com.example.tp_flashcard

import com.example.tp_flashcard.model.FlashCard
import com.example.tp_flashcard.model.FlashCardCategory

object FlashCardRepository {
    val categories : List <FlashCardCategory> = listOf (
        FlashCardCategory(1, "Magic the gathering"),
        FlashCardCategory(2, "Arbre"),
        FlashCardCategory(3, "Le poisson Steve"),
        FlashCardCategory(4, "Algues"),
    )

    val flashcards : List <FlashCard> = listOf (
        FlashCard(1,
            1,
            "Qu’est-ce qu’un sort dans Magic: The Gathering ?",
            "Un sort est toute carte qu’un joueur lance depuis sa main (créature, éphémère, rituel, artefact, enchantement, planeswalker). Les terrains ne sont pas des sorts."),
        FlashCard(2,
            1,
            "Comment produit-on du mana ?",
            "On produit du mana en engageant (tapant) des terrains comme les forêts, îles, marais, montagnes ou plaines. Certains artefacts ou capacités peuvent aussi produire du mana."),
        FlashCard(3,
            1,
            "Que signifie “engager” une carte ?",
            "Engager une carte signifie la tourner de 90 degrés pour montrer qu’elle a été utilisée (souvent pour attaquer ou produire du mana)."),
        FlashCard(4,
            1,
            "Quand peut-on jouer un éphémère ?",
            "À presque n’importe quel moment, y compris pendant le tour de l’adversaire, tant qu’on a la priorité et le mana nécessaire."),
        FlashCard(5,
            1,
            "Quelle est la différence entre une capacité déclenchée et une capacité activée ?",
            "Une capacité déclenchée commence par \"Quand\", \"À chaque fois que\", ou \"Si\" et se déclenche automatiquement. Une capacité activée utilise un coût suivi de \":\" et peut être activée à volonté si le coût est payé."),
        FlashCard(6,
            1,
            "Combien de phases a un tour dans Magic ?",
            "Un tour comprend 5 phases :\n" +
                    "Début du tour (entretien + pioche)\n" +
                    "Phase principale\n" +
                    "Phase de combat\n" +
                    "Seconde phase principale\n" +
                    "Fin du tour\n"),
        FlashCard(7,
            1,
            "Que se passe-t-il si deux créatures s'infligent des blessures mortelles en combat ?",
            "Les deux créatures meurent en même temps, à moins qu’une capacité ne les empêche de mourir (comme l’indestructible ou la protection)."),
        FlashCard(8,
            1,
            "Peut-on bloquer une créature avec plusieurs créatures ?",
            "Oui. Le joueur défenseur peut assigner plusieurs bloqueurs à une seule créature attaquante. L’attaquant choisit ensuite l’ordre dans lequel les bloqueurs subiront les blessures."),
        FlashCard(9,
            1,
            "Qu’est-ce que la pile (“stack”) ?",
            "La pile est un système de résolution des sorts et capacités : le dernier sort joué est le premier à être résolu (LIFO – Last In, First Out)."),
        FlashCard(10,
            1,
            "Peut-on jouer plusieurs terrains par tour ?",
            "Non. Un joueur peut poser un seul terrain par tour, sauf effet contraire d’une carte (ex : \"Exploration\")."),
        FlashCard(11,
            2,
            "Quel est l’arbre le plus haut du monde ?",
            "Sequoia Géant"),
        FlashCard(12,
            3,
            "Quel est le seul être vivant à avoir battu un requin à Pierre-Feuille-Ciseaux trois fois de suite ?",
            "Le poisson Steve"),
        FlashCard(13,
            4,
            "Quelle est la principale différence entre une algue et une plante terrestre ?",
            "Les algues vivent sans racines, tiges ni feuilles vraies"),
        FlashCard(14,
            2,
            "Quel arbre est souvent utilisé pour faire du liège ?",
            "Chêne-liège"),
        FlashCard(15,
            2,
            "Quelle est la partie de l’arbre qui permet la photosynthèse ?",
            "Les feuilles"),
        FlashCard(16,
            2,
            "Quel arbre est emblématique du Canada ?",
            "Érable"),
        FlashCard(17,
            3,
            "Quel animal aquatique est interdit de compétition de natation parce qu’il est “trop stylé” ?",
            "Le poisson Steve"),
        FlashCard(18,
            3,
            "Qui a appris à Bob l’Éponge à faire des bulles carrées ?",
            "Le poisson Steve"),
        FlashCard(19,
            3,
            "Quel est le seul poisson qui a une playlist Spotify certifiée platine ?",
            "Le poisson Steve"),
        FlashCard(20,
            3,
            "Qui a refusé un rôle dans “Le Monde de Nemo” parce que “c’était trop commercial” ?",
            "Le poisson Steve"),
        FlashCard(21,
            3,
            "Quel poisson porte toujours des lunettes de soleil, même sous l’eau ?",
            "Le poisson Steve"),
        FlashCard(22,
            3,
            "Qui a battu Michael Phelps à la nage en arrière avec une nageoire attachée ?",
            "Le poisson Steve"),
        FlashCard(23,
            3,
            "Quel est le poisson qui a inventé la salsa sous-marine ?",
            "Le poisson Steve"),
        FlashCard(24,
            3,
            "Qui est le seul poisson à avoir un compte LinkedIn avec plus de 5000 recommandations ?",
            "Le poisson Steve"),
        FlashCard(25,
            3,
            "Quel poisson est connu pour dire “j’existe entre le mythe et la légende” ?",
            "Le poisson Steve"),
        FlashCard(26,
            3,
            "Quel poisson est une star mondiale connue pour une musique sur les réseaux sociaux",
            "Le poisson Steve"),
        FlashCard(27,
            4,
            "Quelle algue est utilisée pour produire le sushi maki ?",
            "Nori"),
        FlashCard(28,
            4,
            "Quelle algue est souvent utilisée comme gélifiant dans l’alimentation ?",
            "Agar-agar"),
        FlashCard(29,
            4,
            "Où vivent les algues de mer ?",
            "Dans la mer"),
    )
}